tempoPunicaoHoras: 24

mensagens:
  tempoRestante: "&cRenascendo em &f%h%h %m%m"
  morteAssistindo: "&7Você morreu! Agora está assistindo &a%jogador%&7."
  morteSemAlvo: "&7Você morreu, e não há jogadores vivos para assistir. Aguardando renascimento..."
  morteGlobal: "&c%jogador% &7morreu! Ficará fora por &f%horas%h&7."
  reviverAuto: "&aSua punição terminou! Você renasceu no spawn."
  reviverManual: "&aUm administrador o reviveu manualmente."
  reviverGlobal: "&a%jogador% &7foi revivido!"
  bloqueioVisao: "&cVocê não pode trocar de visão enquanto estiver morto."
  bloqueioComando: "&cVocê não pode usar comandos enquanto estiver morto."
