tempoPunicaoHoras: 24

mensagens:
  tempoRestante: "&cRenascendo em &f%h%h %m%m"
  morteAssistindo: "&7Você morreu! Agora está assistindo &a%jogador%&7."
  morteSemAlvo: "&7Você morreu, mas não há jogadores vivos para assistir."
  morteGlobal: "&c%jogador% &7morreu e ficará morto por &f%horas%h."
  reviverAuto: "&aSua punição terminou! Você renasceu automaticamente."
  reviverManual: "&aVocê foi revivido por um administrador."
  reviverGlobal: "&a%jogador% &7foi revivido!"
  bloqueioVisao: "&cVocê não pode trocar de visão enquanto estiver morto."
  bloqueioComando: "&cVocê não pode usar comandos enquanto estiver morto."
