name: ModoMorte99
main: com.nin9.modomorte99.ModoMorte99
version: 1.3
api-version: 1.21
author: NineNine
description: Impede jogadores de reviver por um tempo e adiciona o comando /trocar.
commands:
  reviver:
    description: Revive um jogador morto.
    usage: /reviver <jogador>
  trocar:
    description: Troca a visão para outro jogador enquanto morto.
    usage: /trocar [jogador]
permissions:
  modomorte.reviver:
    description: Permite reviver jogadores manualmente.
    default: op
